import type { IconName } from "./icons";

/** Stable area semantics; translated labels never determine the symbol. */
const SYMBOLS: Record<string, IconName> = {
  work: "monitor",
  team: "monitor",
  study: "book",
  creativeWork: "monitor",
  workingSpot: "monitor",
  meeting: "users",
  discussion: "chat",
  collaboration: "users",
  mabar: "users",
  living: "users",
  reception: "briefcase",
  entrance: "door",
  material: "briefcase",
  pantry: "coffee",
  snack: "coffee",
  rooftopBar: "coffee",
  kitchen: "food",
  bbq: "food",
  bedroom: "bed",
  bathroom: "drop",
  lounge: "sofa",
  gamingLounge: "sofa",
  relax: "leaf",
  terrace: "leaf",
  balcony: "leaf",
  viewpoint: "mountain",
  pcGaming: "controller",
  homeGaming: "controller",
  console: "controller",
  homeStudio: "palette",
  ideas: "bolt",
  content: "cam",
  streaming: "cam",
  cinema: "play",
};
export const zoneIcon = (label: string): IconName => SYMBOLS[label.replace(/^zone\./, "")] ?? "door";
